.TH PEUNWRAP 1 "Thu Jun 21 2012"
.SH NAME
peunwrap \- command line tool for extracting PKCS 7 key lists from PE binaries.

.SH SYNOPSIS
\fBpewrap\fR \fIinput.efi\fR \fIkeyfile.cer\fR

.SH DESCRIPTION
\fBpeunwrap\fR is a command line tool for extracting PKCS 7 keys for use in
UEFI Secure Boot settings from PE binaries.

.SH "SEE ALSO"
.BR efikeygen (1)
.BR pewrap (1)

.SH AUTHORS
.nf
Peter Jones
.fi
