.TH PESIGN 1 "Thu Jun 21 2012"
.SH NAME
pewrap \- command line tool for wrapping PKCS 7 keys in PE binaries.

.SH SYNOPSIS
\fBpewrap\fR \fIkeyfile.cer\fR \fIresult.efi\fR

.SH DESCRIPTION
\fBpewrap\fR is a command line tool for wrapping PKCS 7 keys for use in UEFI
Secure Boot settings in PE binaries.

.SH "SEE ALSO"
.BR efikeygen (1)

.SH AUTHORS
.nf
Peter Jones
.fi
